### ISSUE TITLE
Agent not training with latest version of TF nightly

### ISSUE THREAD

**Issue by sibyjackgrove** [inoryy/tensorflow2-deep-reinforcement-learning#1]
It seems some change in the latest version of TF nightly caused the model to break. Now it is not training at all, and apparent behaving as a randomly initialized network. The same code was working for me and the agent was getting trained till last Sunday (29th). Could you please check what might have gone wrong. 

**Training plot:**
![image](https://user-images.githubusercontent.com/25213730/51927732-dfaba200-23b9-11e9-8870-b4dee96cf796.png)

**TF version:**
![image](https://user-images.githubusercontent.com/25213730/51927791-0669d880-23ba-11e9-8197-5ccbf7507522.png)

**Comment by inoryy** [comment]
Thanks for the report, can reproduce it locally. I'll look into it when I have a moment, but as a temporary workaround please force preview version to the one I've used in the blog, i.e.

```bash
pip install tf-nightly-2.0-preview==1.13.0-dev20190117
```

**Comment by sibyjackgrove** [comment]
Ok, will do that. Thanks!

**Comment by inoryy** [comment]
Fixed!

**Comment by sibyjackgrove** [comment]
Thanks, it works fine now!
