### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by phillipleblanc** [inoryy/tensorflow2-deep-reinforcement-learning#10]
Hi @inoryy,

Thanks for your excellent post on implementing A2C with Tensorflow 2. Would you mind adding a LICENSE to this repository to clarify how people can use this code?

Thanks!

**Comment by inoryy** [comment]
Hello,

Sure, no problem! Added the MIT license in 964fa7d1da8f91d3f766f6b5f9b0195d9616c0c4
